version: '3'
services:
  database:
    image: postgres:9.6
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
  backend:
    build: ./back
    ports:
      - '5000:5000'
    environment:
      DATABASE_URL: postgres://postgres:postgres@database:5432/postgres
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
    depends_on:
      - database
  frontend:
    build: ./front
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - backend
